package contacts;

public enum Actions {
    CONTACT_ADDED,
    CONTACT_DELETED,
    PHONEBOOK_COUNT_VIEWED,
    INFO_FOR_CONTACT_REQUESTED,
    CONTACT_EDITED,
    APPLICATION_STARTED,
    APPLICATION_EXITED,
    SEARCH_QUERY_CONDUCTED
}
